## Time of Day (TOD) section
- platform: tod
  name: Nacht
  after: sunset
  before: sunrise

- platform: tod
  name: Dag
  after: sunrise
  before: sunset

- platform: tod
  name: Slaaptijd
  after: "22:00"
  before: "07:30"

- platform: tod
  name: ochtend
  after: "07:30"
  before: "9:00"

- platform: tod
  name: Overdag
  after: "9:00"
  before: "15:30"

- platform: tod
  name: Avond
  after: "15:30"
  before: "22:00"

- platform: template
  sensors:
    coffee_machine:
      friendly_name: "Koffiezetapparaat"
      delay_off:
        minutes: 3
      value_template: >-
        {{ states('sensor.powerplug004_energy_power') | float > 3 }}
      availability_template: "{{ states('sensor.powerplug004_energy_power') | is_number }}"
