# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
  customize: !include customize.yaml
  country: NL

frontend:
  themes: !include_dir_merge_named themes/
  #######
  ####### Special theme for tablet
  ####### Extra entries for https://github.com/matt8707/hass-config
  #######
  extra_module_url:
    - /hacsfiles/lovelace-card-mod/card-mod.js
  ######

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
utility_meter: !include utility_meter.yaml
light: !include lights.yaml
binary_sensor: !include binary_sensor.yaml
sensor: !include sensors.yaml
switch: !include switch.yaml

#######
####### Recorder entries gaan naar een MariaDB
#######
recorder:
  db_url: !secret mariadb_url

#######
####### InfluxDB section
#######

influxdb:
  # host: homeassist.intern.vanzanten.be
  host: databases.intern.vanzanten.be
  port: 8086
  database: homeassistant
  username: homeassistant
  password: !secret influxdb_password
  max_retries: 3
  default_measurement: state

#######
####### End of: InfluxDB section
#######

#######
####### Configureer welke entities wel/niet in logbook komen
#######
logbook:
  exclude:
    entities:
      - sensor.time_utc
      - sensor.date_time_utc
      - sensor.date_time
      - sensor.date_time_iso
      - sensor.internet_time
      - sensor.time_date
      - sensor.time
      - sensor.total_incoming_energy
      - binary_sensor.water_sensor_status
      - binary_sensor.opentherm_flame_state
      - binary_sensor.auxiliary_dhw_state

#######
####### Configureer logging levels
#######

logger:
  default: info
  logs:
    homeassistant.components.twinkly.light: warn
    homeassistant.components.mqtt: warn

### Text to speech
tts:
  - platform: google_translate

# Example configuration.yaml entry for the Telegram Bot
telegram_bot:
  - platform: polling
    api_key: !secret telegram_api_key
    allowed_chat_ids:
      - 17513465
      - -897405316

# Example configuration.yaml entry for the notifier
notify:
  - name: Telegram
    platform: telegram
    chat_id: 17513465

  - name: HomeGroupTelegram
    platform: telegram
    chat_id: -897405316

  #### Chrome push notifications: https://www.home-assistant.io/integrations/html5
  #### Reference email van firebase: firebase-adminsdk-ok1nu@homeass-chromenotify.iam.gserviceaccount.com
  - platform: html5
    name: GabrieChrome
    vapid_pub_key: !secret vapid_pub_key
    vapid_prv_key: !secret vapid_prv_key
    vapid_email: !secret vapid_email

  ## Een groep om later aan te refereren in automations
  - platform: group
    name: MobieleNotificaties
    services:
      - service: mobile_app_telefoonbas
      - service: mobile_app_telefoondaan
      - service: mobile_app_telefoongabrie

  - platform: group
    name: AlleNotificaties
    services:
      - service: lgtv
      - service: mobile_app_telefoonbas
      - service: mobile_app_telefoondaan
      - service: mobile_app_telefoongabrie
      - service: mobile_app_kiosk

#######
####### Spotcast
####### https://github.com/fondberg/spotcast
#######
spotcast:
  sp_dc: !secret sp_dc
  sp_key: !secret sp_key

#####################################
## Home Connect Alt HACS integratie
#####################################
home_connect_alt:
  client_id: !secret home_connect_client_id
  client_secret: !secret home_connect_client_secret
