# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
  customize: !include customize.yaml
  latitude: !secret latitude
  longitude: !secret longitude

frontend:
  themes: !include_dir_merge_named themes/

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
utility_meter: !include utility_meter.yaml
plant: !include plant.yaml
light: !include lights.yaml
binary_sensor: !include binary_sensor.yaml
sensor: !include sensors.yaml
switch: !include switch.yaml


#######
####### Configureer welke entities wel/niet in logbook komen
#######
logbook:
  exclude:
    entities:
      - sensor.time_utc
      - sensor.date_time_utc
      - sensor.date_time
      - sensor.date_time_iso
      - sensor.internet_time
      - sensor.time_date
      - sensor.time

#######
####### Configureer logging levels
#######

logger:
  default: info
  logs:
    homeassistant.components.twinkly.light: warn
    homeassistant.components.mqtt: warn

### Text to speech
tts:
  - platform: google_translate
    ### service_name: google_say


##########
### Daan Slaapt
#########
template:
  binary_sensor:
    - name: daanslaapt
      unique_id: daanslaapt
      state: >
        {{ is_state('sensor.oneplus_daan_type_oplader','ac')
        and is_state('device_tracker.oneplus_daan','home')
        and is_state('light.daanlamp','off') 
        }}

#####################################################
### Toegevoegd voor Roborock S5 Max
### https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor
#####################################################
camera:
  - platform: xiaomi_cloud_map_extractor
    host: !secret xiaomi_vacuum_host
    token: !secret xiaomi_vacuum_token
    username: !secret xiaomi_cloud_username
    password: !secret xiaomi_cloud_password
    colors:
      color_path: [255, 255, 255]
    draw: ["all"]
    map_transformation:
      scale: 1
      trim:
        top: 20
        bottom: 20
        left: 20
        right: 20
    auto_update: true
    scan_interval:
      seconds: 600 #10minutes
    attributes:
      - calibration_points
      - rooms
      - room_numbers
      - path
      - vacuum_room
      - vacuum_room_name
      - map_name
      - cleaned_rooms
      - zones



#######
####### InfluxDB section
#######

influxdb:
  host: homeassist.intern.vanzanten.be
  port: 8086
  database: homeassistant
  username: homeassistant
  password: !secret influxdb_password
  max_retries: 3
  default_measurement: state

#######
####### End of: InfluxDB section
#######

#######
####### Siemens Home Connect section
####### https://www.home-assistant.io/integrations/home_connect/
## home_connect:
##  client_id: !secret siemens_client_id
##  client_secret: !secret siemens_client_secret
###### Einde Home Connect

# Example configuration.yaml entry for the Telegram Bot
telegram_bot:
  - platform: polling
    api_key: !secret telegram_api_key
    allowed_chat_ids:
      - 17513465

# Example configuration.yaml entry for the notifier
notify:
  - name: Telegram
    platform: telegram
    chat_id: 17513465
  # End of telegram configuration

  #### Chrome push notifications: https://www.home-assistant.io/integrations/html5
  #### Reference email van firebase: firebase-adminsdk-ok1nu@homeass-chromenotify.iam.gserviceaccount.com
  - platform: html5
    name: GabrieChrome
    vapid_pub_key: !secret vapid_pub_key
    vapid_prv_key: !secret vapid_prv_key
    vapid_email: !secret vapid_email

#######
####### Spotcast
####### https://github.com/fondberg/spotcast
#######
spotcast:
  sp_dc: !secret sp_dc
  sp_key: !secret sp_key

#######
####### Spotify integarion
####### https://www.home-assistant.io/integrations/spotify
#######
## spotify:
##  client_id: !secret spotify_client_id
##  client_secret: !secret spotify_client_secret

#####################################
## Google Calendar integratie
#####################################
## google:
##  client_id: !secret googlecalendar_client_id
##  client_secret: !secret googlecalendar_client_secret
##  calendar_access: read_write

#####################################
## Withings Weegschaal configuratie
## https://www.home-assistant.io/integrations/withings/
#####################################
## withings:
##  client_id: !secret withings_CLIENT_ID
##  client_secret: !secret withings_CONSUMER_SECRET

