#######
####### Sensor section
#######

#####################################################
### Toegevoegd om van de s0Tool de versie info uit github op te halen
#####################################################
- platform: rest
  resource: https://api.github.com/repos/huizebruin/s0tool/releases/latest
  name: s0tool_versie_github
  value_template: "​{{ value_json.tag_name }}​"
  scan_interval: 3600

## Om de github versie te vergelijken met de "running" versie van s0tool
- platform: template
  sensors:
    s0tool_gelijk_github:
      friendly_name: "s0Tool versie gelijk github versie"
      value_template: "{{ states('sensor.s0tool_versie_github') | replace(states('sensor.s0tool_versie_github')[0:1],'') == states('sensor.s0tool_versie') }}"

#####################################################
### Toegevoegd om Airco in Energy dashboard te krijgen
#####################################################
- platform: integration
  source: sensor.airco_bas_energy_current
  name: airco bas
  unit_prefix: k
  round: 2

- platform: integration
  source: sensor.airco_daan_energy_current
  name: airco daan
  unit_prefix: k
  round: 2

- platform: integration
  source: sensor.airco_woonkamer_energy_current
  name: airco woonkamer
  unit_prefix: k
  round: 2
#####################################################
### EINDE Toegevoegd om Airco in Energy dashboard te krijgen
#####################################################

- platform: integration
  source: sensor.s0tool_versie_github
  name: "S0tool GitHub Versie"

#################################
###### Sensor for vacuum cleaner
#################################
- platform: template
  sensors:
    next_vacuum_date:
      friendly_name: "Stofzuiger - Volgende Stofzuigmoment"
      value_template: >-
        {% set day_values = [ states('input_boolean.vacuum_monday'), 
        states('input_boolean.vacuum_tuesday'), 
        states('input_boolean.vacuum_wednesday'), 
        states('input_boolean.vacuum_thursday'), 
        states('input_boolean.vacuum_friday'), 
        states('input_boolean.vacuum_saturday'), 
        states('input_boolean.vacuum_sunday')] %}
        {% set start_time = states('input_datetime.vacuum_schedule_start_time') %}
        {% set start_index = 0 %}
        {% if as_timestamp(now()) > as_timestamp((as_timestamp(now()) | timestamp_custom('%Y-%m-%d')) + ' ' + start_time) %}
          {% set start_index = 1 %}
        {% endif %}
        {% set ns = namespace(next_vacuum_date = undefined) %}
        {% for i in range(start_index, 6) if ns.next_vacuum_date is undefined %}
          {% set weekday = now().weekday() + i %}
          {% if weekday > 6 %}
            {% set weekday = weekday - 7 %}
          {% endif %}
          {% if day_values[weekday] == 'on' %}
            {% set vacuum_date = ((as_timestamp(now()) | int) + (i * 24 * 3600)) | timestamp_custom('%Y-%m-%d') %}
            {% set ns.next_vacuum_date = strptime(vacuum_date + ' ' + start_time, '%Y-%m-%d %H:%M:%S') %}
          {% endif %}
        {% endfor%}  
        {{ ns.next_vacuum_date }}

###### Sensor for vacuum cleaner
- platform: template
  sensors:
    vacuum_day:
      friendly_name: "Stofzuiger - Stofzuigdag"
      value_template: >-
        {% set weekday = as_timestamp(now()) | timestamp_custom('%A') | lower %}
        {{ states('input_boolean.vacuum_' + weekday) }}

##### Sensor voor Bas Wekker
- platform: template
  sensors:
    baswekker_day:
      friendly_name: "Bas Wekker dag"
      value_template: >-
        {% set weekday = as_timestamp(now()) | timestamp_custom('%A') | lower %}
        {{ states('input_boolean.baswekker_' + weekday) }}

# Optional/example
# A template to ease access to the data as "sensor.pv_outputpower" etc.
- platform: template
  sensors:
    pv_outputpower:
      value_template: "{{ states.sensor.inverter_goodwe.attributes.outputpower }}"
      unit_of_measurement: "W"
      friendly_name: "PV Power output"
    pv_temperature:
      value_template: "{{ states.sensor.inverter_goodwe.attributes.tempperature }}"
      unit_of_measurement: "C"
      friendly_name: "PV Temperature"
    pv_eday:
      value_template: "{{ states.sensor.inverter_goodwe.attributes.eday }}"
      unit_of_measurement: "kWh"
      friendly_name: "PV energy day"
    pv_etotal:
      value_template: "{{ states.sensor.inverter_goodwe.attributes.etotal }}"
      unit_of_measurement: "kWh"
      friendly_name: "PV energy total"
    pv_iday:
      value_template: "{{ states.sensor.inverter_goodwe.attributes.iday }}"
      unit_of_measurement: "€"
      friendly_name: "PV income day"
    pv_itotal:
      value_template: "{{ states.sensor.inverter_goodwe.attributes.itotal }}"
      unit_of_measurement: "€"
      friendly_name: "PV income total"
    pv_excess:
      value_template: "{{ states.sensor.inverter_goodwe.attributes.pmeter }}"
      unit_of_measurement: "W"
      friendly_name: "PV spare"
    # battery soc
    pv_soc:
      value_template: "{{ states.sensor.inverter_goodwe.attributes.soc }}"
      unit_of_measurement: "%"
      friendly_name: "Battery power"

- platform: template
  sensors:
    airco_bas_current_temp:
      friendly_name: "Airco Bas kamer temperatuur"
      unit_of_measurement: "degrees"
      value_template: "{{ state_attr('climate.airco_bas', 'current_temperature') }}"
    airco_bas_target_temp:
      friendly_name: "Airco Bas doel temperatuur"
      unit_of_measurement: "degrees"
      value_template: "{{ state_attr('climate.airco_bas', 'temperature') }}"

    airco_woonkamer_current_temp:
      friendly_name: "Airco Woonkamer temperatuur"
      unit_of_measurement: "degrees"
      value_template: "{{ state_attr('climate.airco_woonkamer', 'current_temperature') }}"
    airco_woonkamer_target_temp:
      friendly_name: "Airco Woonkamer doel temperatuur"
      unit_of_measurement: "degrees"
      value_template: "{{ state_attr('climate.airco_woonkamer', 'temperature') }}"

    airco_daan_current_temp:
      friendly_name: "Airco Daan kamer temperatuur"
      unit_of_measurement: "degrees"
      value_template: "{{ state_attr('climate.airco_daan', 'current_temperature') }}"
    airco_daan_target_temp:
      friendly_name: "Airco Daan kamer doel temperatuur"
      unit_of_measurement: "degrees"
      value_template: "{{ state_attr('climate.airco_daan', 'temperature') }}"

## Sensor om de attributen van sun.sun in automations te kunnen gebruiken
- platform: template
  sensors:
    solar_angle:
      friendly_name: "Sun angle"
      unit_of_measurement: "degrees"
      value_template: "{{ state_attr('sun.sun', 'elevation') }}"
    solar_azimuth:
      friendly_name: "Sun azimuth"
      unit_of_measurement: "degrees"
      value_template: "{{ state_attr('sun.sun', 'azimuth') }}"
    sunrise:
      value_template: "{{ state_attr('sun.sun', 'next_rising') }}"
    sunset:
      value_template: "{{ state_attr('sun.sun', 'next_setting') }}"
    sundawn:
      value_template: "{{ state_attr('sun.sun', 'next_dawn') }}"
    sundusk:
      value_template: "{{ state_attr('sun.sun', 'next_dusk') }}"
    sunrising:
      value_template: "{{ state_attr('sun.sun', 'rising') }}"

# Example configuration.yaml entry
- platform: time_date
  display_options:
    - "time"
    - "date"
    - "date_time"
    - "date_time_utc"
    - "date_time_iso"
    - "time_date"
    - "time_utc"

########################################
## Plant moisture sectie alarm
########################################
- platform: template
  sensors:
    plant_01_alarm:
      friendly_name: "Plant boekenkast"
      value_template: "{{ states('sensor.esp32ble_plant_01_moisture') | float(100) < 20  }}"
      ## value_template: "{{ state_attr('plant.1boekenkast','moisture') | default(0) < 20  }}"

- platform: template
  sensors:
    plant_02_alarm:
      friendly_name: "Plant salontafel krukje"
      value_template: "{{ states('sensor.esp32ble_plant_02_moisture') | float(100) < 20  }}"
      ## value_template: "{{ state_attr('plant.2aglonema_sp','moisture') | default(0) < 20  }}"

- platform: template
  sensors:
    plant_03_alarm:
      friendly_name: "Pannekoekenplant"
      value_template: "{{ states('sensor.esp32ble_plant_03_moisture') | float(100) < 20  }}"
      ## value_template: "{{ state_attr('plant.3pilea_peperomioides','moisture') | default(0) < 20  }}"

- platform: template
  sensors:
    plant_04_alarm:
      friendly_name: "Plant salontafel plankje"
      value_template: "{{ states('sensor.esp32ble_plant_04_moisture') | float(100) < 20  }}"
      ## value_template: "{{ state_attr('plant.4philondendron_white_measure','moisture') | default(0) < 20  }}"

- platform: template
  sensors:
    plant_05_alarm:
      friendly_name: "Plant naast TV"
      value_template: "{{ states('sensor.esp32ble_plant_05_moisture') | float(100) < 20  }}"
      ## value_template: "{{ state_attr('plant.5naastv','moisture') | default(0) < 20  }}"

###################################
## BMW Tank alarm
###################################
- platform: template
  sensors:
    bmw_tanken:
      friendly_name: "BMW Tanken"
      value_template: "{{ states('sensor.state_of_charge_predicted_on_integration_side') | float(0) < 15  }}"
      icon_template: mdi:gas-station

###################################
## Adhv tijdstip electriciteitsprijs bepalen
###################################
- platform: template
  sensors:
    current_electricity_rate:
      value_template: >-
        {% set curtime = strptime(states('sensor.time'), '%H:%M') %}
        {% if curtime.hour >= 7 and curtime.hour <= 21 and is_state('binary_sensor.workday_sensor', 'on') -%} 0.15080 
        {%- else -%} 0.13727
        {%- endif -%}
      friendly_name: Current Electricity Rate
      unit_of_measurement: EUR/kWh

###################################
## Stopcontact07 geschikt maken voor energy dashboard
###################################
- platform: integration
  source: sensor.stopcontact07_power
  name: computers bureau
  unit_prefix: k
  round: 2

###################################
## Totaal inkomende energy voor SANKEY card
###################################
- platform: template
  sensors:
    total_incoming_energy:
      value_template: >-
        {{ states('sensor.power_usage')|float(0) + states('sensor.inverter_goodwe')|float(0) }}

###################################
## Verbruikt dan wadroger meer dan 5W, dan is ie actief
###################################
- platform: template
  sensors:
    wasdroger_actief:
      friendly_name: wasdroger loopt
      value_template: "{{ states('sensor.wassensor.wasdroger_tz3000_u5u4cakc_ts011f_1cce85fe_electrical_measurement') | int(0) > 5.0 }}"

###################################
## Verbruikt dan wadroger meer dan 5W, dan is ie actief
###################################
- platform: template
  sensors:
    wasmachine_actief:
      friendly_name: wasmachine loopt
      value_template: "{{ states('sensor.powerplug002_wasmachine_energy_power') | int(0) > 5.0 }}"

###################################
## Energy Zero tarieven
## https://student-techlife.com/2023/01/11/energyzero-market-prices-with-new-integration-in-home-assistant/
###################################

- platform: template
  sensors:
    energyzero_allin_energy_current_price:
      friendly_name: EnergyZero all-in current energy price
      unit_of_measurement: "€/kWh"
      # state_class: measurement
      value_template: >
        {% set energy_tax = 0.1312 %}
        {% set purch_costs = 0.0484 %}
        {% set current_price = states('sensor.energyzero_today_energy_current_hour_price') | float | default(None) %}
        {{ (current_price + energy_tax + purch_costs) | round(2) }}

- platform: template
  sensors:
    energyzero_allin_gas_current_price:
      friendly_name: EnergyZero all-in current gas price
      unit_of_measurement: "€/m³"
      # state_class: measurement
      value_template: >
        {% set energy_tax = 0.7065 %}
        {% set purch_costs = 0.05911 %}
        {% set current_price = states('sensor.energyzero_today_gas_current_hour_price') | float | default(None) %}
        {{ (current_price + energy_tax + purch_costs) | round(4) }}

###################################
## Kleenex Pollen Radar
## https://github.com/MarcoGos/kleenex_pollenradar
###################################
- platform: template
  sensors:
    tree_pollen_day_0:
      friendly_name: Tree pollen today
      unit_of_measurement: ppm
      value_template: >
        {{ states('sensor.kleenex_pollen_radar_pollenmaastricht_trees') }}

- platform: template
  sensors:
    tree_pollen_day_1:
      friendly_name: Tree pollen tomorrow
      unit_of_measurement: ppm
      value_template: >
        {{ state_attr('sensor.kleenex_pollen_radar_pollenmaastricht_trees', 'forecast')[0].value }}

- platform: template
  sensors:
    tree_pollen_day_2:
      friendly_name: Tree pollen day after tomorrow
      unit_of_measurement: ppm
      value_template: >
        {{ state_attr('sensor.kleenex_pollen_radar_pollenmaastricht_trees', 'forecast')[1].value }}

###################################
## Hazelaar info
###################################

- platform: template
  sensors:
    tree_pollen_hazelaar_day_0:
      friendly_name: Hazelaar pollen today
      unit_of_measurement: ppm
      value_template: >
        {{ state_attr('sensor.kleenex_pollen_radar_pollenmaastricht_trees', 'details')[0].value }}

- platform: template
  sensors:
    tree_pollen_hazelaar_day_1:
      friendly_name: Hazelaar pollen tomorrow
      unit_of_measurement: ppm
      value_template: >
        {{ state_attr('sensor.kleenex_pollen_radar_pollenmaastricht_trees', 'forecast')[0].details[0].value }}

- platform: template
  sensors:
    tree_pollen_hazelaar_day_2:
      friendly_name: Hazelaar pollen day after tomorrow
      unit_of_measurement: ppm
      value_template: >
        {{ state_attr('sensor.kleenex_pollen_radar_pollenmaastricht_trees', 'forecast')[1].details[0].value }}

###################################
## Els info
###################################

- platform: template
  sensors:
    tree_pollen_els_day_0:
      friendly_name: Els pollen today
      unit_of_measurement: ppm
      value_template: >
        {{ state_attr('sensor.kleenex_pollen_radar_pollenmaastricht_trees', 'details')[3].value }}

- platform: template
  sensors:
    tree_pollen_els_day_1:
      friendly_name: Els pollen tomorrow
      unit_of_measurement: ppm
      value_template: >
        {{ state_attr('sensor.kleenex_pollen_radar_pollenmaastricht_trees', 'forecast')[0].details[3].value }}

- platform: template
  sensors:
    tree_pollen_els_day_2:
      friendly_name: Els pollen day after tomorrow
      unit_of_measurement: ppm
      value_template: >
        {{ state_attr('sensor.kleenex_pollen_radar_pollenmaastricht_trees', 'forecast')[1].details[3].value }}

###################################
## Berk info
###################################

- platform: template
  sensors:
    tree_pollen_berk_day_0:
      friendly_name: Berk pollen today
      unit_of_measurement: ppm
      value_template: >
        {{ state_attr('sensor.kleenex_pollen_radar_pollenmaastricht_trees', 'details')[7].value }}

- platform: template
  sensors:
    tree_pollen_berk_day_1:
      friendly_name: Berk pollen tomorrow
      unit_of_measurement: ppm
      value_template: >
        {{ state_attr('sensor.kleenex_pollen_radar_pollenmaastricht_trees', 'forecast')[0].details[7].value }}

- platform: template
  sensors:
    tree_pollen_berk_day_2:
      friendly_name: Berk pollen day after tomorrow
      unit_of_measurement: ppm
      value_template: >
        {{ state_attr('sensor.kleenex_pollen_radar_pollenmaastricht_trees', 'forecast')[1].details[7].value }}

##################
## HA en Database snapshot
##################
- platform: template
  sensors:
    esxi_homeassistant_snapshot:
      friendly_name: Home Assistant VM Snapshot
      value_template: >
        {{ state_attr('sensor.esxi_vm_homeassistant', 'snapshots') }}

- platform: template
  sensors:
    esxi_database_snapshot:
      friendly_name: Home Assistant Database VM Snapshot
      value_template: >
        {{ state_attr('sensor.esxi_vm_databases', 'snapshots') }}
