views:
  - theme: Backend-selected
    title: Home
    icon: ''
    type: custom:masonry-layout
    visible:
      - user: 494bc6778e5544cbad2b565c5ba4263f
      - user: 0985600280104456bc63c81caaf9ee3e
    badges: []
    cards:
      - type: custom:layout-card
        layout_type: masonry
        layout:
          width: 1000
        aspect_ratio: 100%
        cards:
          - square: false
            columns: 3
            type: grid
            cards:
              - square: false
                columns: 1
                type: grid
                cards:
                  - type: gauge
                    entity: sensor.power_usage
                    max: 10000
                    min: -4000
                    name: Stroom verbruik
                    severity:
                      green: -1000
                      red: 10000
                      yellow: 2000
                  - type: gauge
                    entity: sensor.pv_outputpower
                    max: 4500
                    min: 0
                    name: Zonne-energie
                    severity:
                      green: 1500
                      red: 4500
                      yellow: 3000
                  - type: gauge
                    entity: sensor.energy_next_hour
                    max: 10000
                    min: -4000
                    name: Verwacht +1 uur
                    severity:
                      green: -1000
                      red: 10000
                      yellow: 2000
                  - type: weather-forecast
                    entity: weather.openweathermap
                    name: OpenWeatherMap
                  - type: entities
                    entities:
                      - entity: sensor.openweathermap_forecast_condition
                        name: Weer
                      - entity: sensor.openweathermap_rain
                        name: Neerslag nu
                      - entity: sensor.openweathermap_forecast_precipitation
                        icon: mdi:weather-rainy
                        name: Voorspelling
                        secondary_info: last-updated
                    title: Voorspelling
                    state_color: true
                  - type: conditional
                    conditions:
                      - entity: sensor.afvalinfo_trash_type_today
                        state_not: none
                    card:
                      type: entity
                      entity: sensor.afvalinfo_trash_type_today
                      name: Afval vandaag
                  - type: conditional
                    conditions:
                      - entity: sensor.afvalinfo_trash_type_tomorrow
                        state_not: none
                    card:
                      type: entity
                      entity: sensor.afvalinfo_trash_type_tomorrow
                      name: Afval Morgen
                  - type: conditional
                    conditions:
                      - entity: sensor.s0tool_gelijk_github
                        state_not: 'True'
                    card:
                      type: markdown
                      content: De s0tool is niet up to date met de GitHub versie.
                  - type: conditional
                    conditions:
                      - entity: sensor.dracaena_marginata_alarm
                        state: 'True'
                    card:
                      type: entity
                      entity: sensor.esp32ble_dracaena_marginata_moisture
                      name: Plant bij de boekenkast is te droog
                  - type: conditional
                    conditions:
                      - entity: sensor.anthurium_andraeanum_white_champion_alarm
                        state: 'True'
                    card:
                      type: entity
                      entity: >-
                        sensor.esp32ble_anthurium_andraeanum_white_champion_moisture
                      name: Plant met de witte bloem is te droog
                  - type: conditional
                    conditions:
                      - entity: sensor.aglaonema_sp_light_star_alarm
                        state: 'True'
                    card:
                      type: entity
                      entity: sensor.esp32ble_aglaonema_sp_light_star_moisture
                      name: Plant met rode bladeren
                  - type: conditional
                    conditions:
                      - entity: sensor.bmw_tanken
                        state: 'True'
                    card:
                      type: entity
                      entity: sensor.bmw_tanken
                      attribute: friendly_name
                      name: ' '
              - square: false
                columns: 1
                type: grid
                cards:
                  - type: entities
                    entities:
                      - entity: sensor.afvalinfo_gft
                        name: GFT bak
                      - entity: sensor.afvalinfo_restafval
                        name: Rest afval
                        icon: mdi:trash-can
                      - entity: sensor.afvalinfo_trash_type_today
                        name: Afval vandaag
                      - entity: sensor.afvalinfo_trash_type_tomorrow
                        name: Afval morgen
                        title: Afval Maastricht
                        state_color: true
                  - type: gauge
                    entity: sensor.anna_temperature
                    needle: true
                    max: 30
                    min: 10
                    segments:
                      - from: 10
                        color: blue
                      - from: 16
                        color: yellow
                      - from: 18
                        color: green
                      - from: 22
                        color: orange
                      - from: 25
                        color: red
                  - type: custom:simple-thermostat
                    entity: climate.anna
                    step_size: '0.5'
                    hide:
                      temperature: true
                      state: true
                    layout:
                      step: row
                      mode:
                        names: false
                        headings: false
                    header:
                      icon: auto
                      name: Woonkamer Anna
                    control:
                      preset:
                        away:
                          name: Niet thuis
                          icon: mdi:walk
                        home:
                          name: Thuis
                          icon: mdi:home
                        asleep:
                          name: Nacht
                          icon: mdi:weather-night
                        vacation: false
                        no_frost: false
                      hvac: true
                  - type: custom:simple-thermostat
                    entity: climate.airco_woonkamer
                    step_size: '0.5'
                    hide:
                      temperature: false
                      state: true
                    label:
                      temperature: Huidig
                    layout:
                      step: row
                      mode:
                        names: false
                        headings: false
                    header:
                      icon: auto
                      name: Woonkamer Airco
                    control:
                      hvac:
                        heat: true
                        cool: true
                        dry: false
                        fan_only: false
                        heat_cool: true
                  - type: glance
                    show_name: true
                    show_icon: true
                    show_state: false
                    entities:
                      - entity: climate.airco_woonkamer
                      - entity: climate.airco_bas
                      - entity: climate.airco_daan
                    state_color: true
                  - type: glance
                    show_name: true
                    show_icon: true
                    show_state: false
                    entities:
                      - entity: binary_sensor.ewelink_ds01_4c3f2622_ias_zone
                        name: voor
                      - entity: binary_sensor.achterdeur_ias_zone
                        name: achter
                      - entity: binary_sensor.ewelink_ds01_f8283622_ias_zone
                        name: schuifpui
                      - entity: binary_sensor.ewelink_ds01_4ccd2622_ias_zone
                        name: poort
                    state_color: true
                  - type: grid
                    cards:
                      - type: button
                        tap_action:
                          action: toggle
                        entity: script.scr006_gordijnen_overdag
                        icon: mdi:blinds-open
                        name: Open
                      - type: button
                        tap_action:
                          action: toggle
                        entity: script.rolgordijnen_omlaag
                        name: Gesloten
                        show_state: false
                    columns: 2
              - square: false
                columns: 1
                type: grid
                cards:
                  - type: entities
                    entities:
                      - entity: light.boekenlamp
                        name: Boekenkast
                      - entity: light.muurlamp
                        name: Schilderijen
                      - entity: light.tafellamp
                        name: Grote tafel
                      - entity: light.computerlamp
                        name: Bureau
                    title: Achterkamer
                  - type: entities
                    entities:
                      - entity: light.tv_lamp
                      - entity: light.led_bank_level_light_color_on_off
                        name: Bank LED
                      - entity: light.staanderaamlamp_level_light_color_on_off
                        name: Raam lamp
                      - entity: >-
                          light.ikea_of_sweden_tradfri_bulb_gu10_cws_345lm_1339b7fe_level_light_color_on_off
                        name: Backlight
                        icon: mdi:spotlight
                    title: Voorkamer
                  - type: entities
                    entities:
                      - entity: light.bas_bed
                        name: Bed LED
                      - entity: light.led_bas_bureau
                        name: Bureau
                      - entity: switch.0xcc86ecfffe3ab9b3
                        name: LED slang
                    title: Kamer Bas
                  - type: entities
                    entities:
                      - entity: light.daanlamp
                        name: Plafondlamp
                    title: Kamer Daan
                    show_header_toggle: true
                  - type: entities
                    entities:
                      - entity: light.signify_netherlands_b_v_llc020_huelight
                        name: Lampje links
                      - entity: light.signify_netherlands_b_v_llc020_huelight_2
                        name: Lampje rechts
                      - entity: light.plafondlamp_gabrie
                        name: Plafond
                    title: Slaapkamer Gabrie
                  - type: entities
                    entities:
                      - entity: light.tuinlamp_links
                        name: Tuin links
                      - entity: light.gardenpost_rgb_cct_2
                        name: Tuin rechts
                      - entity: light.tuinschijnwerper
                        name: Schijnwerper
                        icon: mdi:spotlight-beam
                      - entity: light.twinkly_1e806d
                        name: Slinger
                    title: Tuin
                  - type: entities
                    entities:
                      - entity: light.badkamerlamp
                    title: Badkamer
                  - type: entities
                    entities:
                      - entity: light.voordeurlamp
                        name: Voordeur
                      - entity: light.ganglampbeneden
                        name: Gang onder
                      - entity: light.ganglampboven
                        name: Gang boven
                    title: Gang
