views:
  - title: Woonkamer
    path: woonkamerbuttons
    badges: []
    cards:
      - type: grid
        cards:
          - type: button
            entity: script.scr006_gordijnen_overdag
            name: Gordijnen Open
            icon: hass:blinds-open
            tap_action:
              action: call-service
              service: script.scr006_gordijnen_overdag
              service_data: {}
              target: {}
          - type: button
            name: Gordijnen Dicht
            icon: hass:blinds
            entity: script.rolgordijnen_omlaag
            tap_action:
              action: call-service
              service: script.rolgordijnen_omlaag
              service_data: {}
              target: {}
          - type: button
            tap_action:
              action: none
            show_state: true
            entity: media_player.woonkamer_thuis
            icon: mdi:netflix
          - type: button
            tap_action:
              action: none
            name: TV verlichting
            icon: mdi:television
            entity: script.scr018_achterkamer_spots
          - type: light
            entity: light.achterkamer
            name: Achter
          - type: light
            entity: light.voorkamer
            name: Voor
          - type: light
            entity: light.computerlamp
            icon: mdi:desk-lamp
          - type: button
            tap_action:
              action: toggle
            entity: script.scr015_bank_led_instellen
            name: Bank sfeer
          - type: button
            tap_action:
              action: toggle
            entity: script.scr016_raam_lamp_fel
            name: Raamlamp fel
          - type: button
            tap_action:
              action: toggle
            entity: script.scr017_raam_lamp_sfeer
            icon: mdi:candle
            name: Raamlamp sfeer
          - type: button
            tap_action:
              action: toggle
            entity: switch.tz3000_g5xawfcq_ts0121_on_off
            name: Kerstboom
            icon: mdi:pine-tree
        columns: 2
      - type: grid
        cards:
          - type: custom:simple-thermostat
            entity: climate.anna
            layout:
              step: row
              mode:
                names: true
                icons: true
            header:
              name: Anna Woonkamer
            control: false
          - type: custom:simple-thermostat
            entity: climate.airco_woonkamer
            layout:
              step: row
            header:
              name: Airo Woonkamer
              toggle:
                entity: climate.airco_woonkamer
            control: false
          - type: sensor
            entity: sensor.anna_temperature
            graph: line
            name: Woonkamer Temperatuur
        columns: 1
        square: false
  - title: Kamer Daan
    path: kamer-daan-buttons
    badges: []
    cards:
      - type: grid
        cards:
          - type: grid
            cards:
              - show_name: true
                show_icon: true
                type: button
                entity: script.scr019_kalender_vissen_gevoerd
                name: Vissen Gevoerd
                tap_action:
                  action: call-service
                  service: script.scr019_kalender_vissen_gevoerd
                  service_data: {}
                  target: {}
              - type: button
                tap_action:
                  action: toggle
                entity: switch.powerplug003
                show_state: true
                name: Deken Daan
                icon: mdi:bed
              - type: button
                tap_action:
                  action: toggle
                entity: light.daanlamp
                name: Plafond Lamp
                show_state: true
              - type: thermostat
                entity: climate.airco_daan
            columns: 2
            square: false
          - type: gauge
            entity: input_number.voer_zakjes
            min: 0
            max: 50
            needle: true
            name: Zakjes voer
            severity:
              green: 10
              yellow: 3
              red: 0
          - type: custom:numberbox-card
            border: true
            entity: input_number.voer_zakjes
          - type: entities
            entities:
              - entity: sensor.apk_expiration_2
              - entity: sensor.ascription_date_2
              - entity: binary_sensor.liability_insured_2
              - entity: binary_sensor.pending_recall_2
            title: 'Mazda: 69NPXV'
        columns: 1
        square: false
  - title: Kamer Bas
    path: kamerbas
    badges: []
    cards:
      - type: grid
        cards:
          - show_name: true
            show_icon: true
            type: button
            tap_action:
              action: toggle
            entity: script.scr014_bas_vertraagd_led_slang_uit
            name: Langzaam uit
            show_state: true
            icon: mdi:clock
          - type: light
            entity: light.bas_bed
            name: Bed
            double_tap_action:
              action: toggle
            icon: mdi:bed
          - type: light
            entity: light.led_bas_bureau
            name: Bureau
            icon: mdi:desk
          - type: thermostat
            entity: climate.airco_bas
          - type: light
            entity: light.kamerbas
            double_tap_action:
              action: toggle
          - show_name: true
            show_icon: true
            type: button
            entity: switch.0xcc86ecfffe3ab9b3
            icon: mdi:led-strip
            tap_action:
              action: toggle
            name: LED Slang
        columns: 2
      - type: entities
        entities:
          - entity: input_boolean.baswekker_enabled
            name: Wekker Actief
            icon: mdi:alarm-check
          - entity: input_datetime.baswekker_schedule_start_time
            name: Tijdstip
          - entity: input_boolean.baswekker_monday
            name: Maandag
          - entity: input_boolean.baswekker_tuesday
            name: Dinsdag
          - entity: input_boolean.baswekker_wednesday
            name: Woensdag
          - entity: input_boolean.baswekker_thursday
            name: Donderdag
          - entity: input_boolean.baswekker_friday
            name: Vrijdag
          - entity: input_boolean.baswekker_saturday
            name: Zaterdag
          - entity: input_boolean.baswekker_sunday
            name: Zondag
        title: Bas Wekker
        state_color: true
        show_header_toggle: false
      - type: media-control
        entity: media_player.googlehome5415
        theme: dark_red
  - title: Verlichting
    path: verlichtingbuttons
    badges: []
    cards:
      - type: grid
        cards:
          - type: button
            tap_action:
              action: toggle
            show_state: true
            entity: light.voorkamer
            icon: hass:television
            name: Voorkamer
          - type: button
            tap_action:
              action: toggle
            entity: light.achterkamer
            name: Achterkamer
            icon: mdi:book-open-variant
            show_state: true
            hold_action:
              action: toggle
          - type: button
            tap_action:
              action: toggle
            name: Woonkamer alles
            icon: hass:home-map-marker
            show_state: true
            entity: light.woonkamertotaal
          - type: light
            entity: light.computerlamp
            icon: mdi:spotlight
          - type: button
            tap_action:
              action: toggle
            name: Gang boven / onder
            icon: mdi:stairs
            show_state: true
            entity: light.gang
          - type: button
            tap_action:
              action: toggle
            entity: light.daanlamp
            name: Kamer Daan
            icon: mdi:horse-variant
          - type: button
            tap_action:
              action: toggle
            entity: light.kamerbas
            name: Kamer Bas
            icon: mdi:controller-classic
          - type: button
            tap_action:
              action: toggle
            entity: light.slaapkamergabrie
            icon: mdi:bed
            name: Kamer Gabrie
          - type: button
            tap_action:
              action: toggle
            icon: mdi:shower
            show_state: false
            name: Badkamer
            entity: light.badkamerlamp
          - type: button
            tap_action:
              action: toggle
            name: Tuin
            icon: hass:shovel
            show_state: false
            entity: light.tuinverlichting
            hold_action:
              action: toggle
        columns: 2
  - title: Tuin
    path: tuin
    badges: []
    cards:
      - type: grid
        cards:
          - type: light
            entity: light.tuinlamp_links
            icon: mdi:floor-lamp
          - type: light
            entity: light.gardenpost_rgb_cct_2
            icon: mdi:floor-lamp
          - type: light
            entity: light.twinkley_tuinslinger
            name: Slinger
          - show_name: true
            show_icon: true
            type: button
            tap_action:
              action: toggle
            entity: light.tuinschijnwerper
            name: Schijnwerper
            icon: mdi:lighthouse-on
        columns: 2
  - theme: Backend-selected
    title: BBQ
    path: bbq
    icon: mdi:grill
    badges: []
    cards:
      - type: grid
        cards:
          - type: sensor
            entity: sensor.meater_probe_ambient
            name: BBQ
            hours_to_show: 4
            graph: line
          - hours_to_show: 4
            graph: line
            type: sensor
            entity: sensor.meater_probe_internal
            detail: 1
      - type: grid
        cards:
          - type: sensor
            entity: sensor.meater_probe_ambient_2
            name: BBQ
            hours_to_show: 4
            graph: line
          - hours_to_show: 4
            graph: line
            type: sensor
            entity: sensor.meater_probe_internal_2
            detail: 1
      - type: grid
        cards:
          - type: sensor
            entity: sensor.meater_probe_ambient_3
            name: BBQ
            hours_to_show: 4
            graph: line
          - hours_to_show: 4
            graph: line
            type: sensor
            entity: sensor.meater_probe_internal_3
            detail: 1
      - type: grid
        cards:
          - type: sensor
            entity: sensor.meater_probe_ambient_4
            name: BBQ
            hours_to_show: 4
            graph: line
          - hours_to_show: 4
            graph: line
            type: sensor
            entity: sensor.meater_probe_internal_4
            detail: 1
      - chart_type: line
        period: 5minute
        days_to_show: 1
        type: statistics-graph
        entities:
          - sensor.meater_probe_ambient
          - sensor.meater_probe_ambient_2
          - sensor.meater_probe_ambient_3
          - sensor.meater_probe_ambient_4
        stat_types:
          - mean
        title: Vlees temp
      - chart_type: line
        period: 5minute
        days_to_show: 1
        type: statistics-graph
        entities:
          - sensor.meater_probe_internal
          - sensor.meater_probe_internal_2
          - sensor.meater_probe_internal_3
          - sensor.meater_probe_internal_4
        stat_types:
          - mean
        title: Vlees temp
